[[main]]
  identifier = "home"
  name       = "主页"
  url        = "/"
  weight     = 1

  [main.params]
    icon = "home"

[[main]]
  identifier = "notes"
  name       = "知识"
  url        = "/notes/"
  weight     = 2

  [main.params]
    icon = "book"

[[main]]
  identifier = "reference"
  name       = "速查"
  url        = "/reference/"
  weight     = 3

  [main.params]
    icon = "categories"

[[main]]
  identifier = "categories"
  name       = "分类"
  url        = "/categories/"
  weight     = 5

  [main.params]
    icon = "tag"

[[main]]
  identifier = "archives"
  name       = "归档"
  url        = "/archives/"
  weight     = 6

  [main.params]
    icon = "archives"

[[main]]
  identifier = "search"
  name       = "搜索"
  url        = "/search/"
  weight     = 7

  [main.params]
    icon = "search"

[[main]]
  identifier = "about"
  name       = "关于"
  url        = "/about/"
  weight     = 8

  [main.params]
    icon = "user"

[[main]]
  identifier = "links"
  name       = "链接"
  url        = "/links/"
  weight     = 9

  [main.params]
    icon = "link"

[[main]]
  identifier = "resources"
  name       = "资源库"
  url        = "/resources/"
  weight     = 4

  [main.params]
    icon = "resources"

[[social]]
  identifier = "github"
  name       = "GitHub"
  url        = "https://github.com/"

  [social.params]
    icon = "brand-github"
